{
 "title": "APM Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Levitate Instance", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(http_requests_total{}, environment)"
    }
   },
   {
    "name": "program",
    "label": "Program",
    "query": {
     "query": "label_values(http_requests_total{}, program)"
    }
   },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(http_requests_total{}, version)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(http_requests_total{}, host)"
    }
   },
   {
    "name": "ip",
    "label": "IP Address",
    "query": {
     "query": "label_values(http_requests_total{}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Web Transactions Time (percentile)",
   "type": "timeseries",
   "description": "This metric measures the response time percentiles of web transactions, indicating the distribution of transaction response times.\n\nAggregation: Percentiles (e.g., 50th percentile, 90th percentile, 99th percentile)",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(http_requests_duration_milliseconds_bucket{program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[1m])))",
     "legendFormat": "Duration (95%)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(http_requests_duration_milliseconds_bucket{program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[1m])))",
     "legendFormat": "Duration (99%)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(http_requests_duration_milliseconds_bucket{program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[1m])))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Appdex Score",
   "type": "timeseries",
   "description": "The Apdex score is a ratio value of the number of satisfied and tolerating requests to the total requests made. Each satisfied request counts as one request, while each tolerating request counts as half a satisfied request.\n\nAn Apdex score varies from 0 to 1, with 0 as the worst possible score (100% of response times were Frustrated), and 1 as the best possible score (100% of response times were Satisfied).\n\nAppDex Score = (Weighted Sum of Request Counts within Thresholds) / (Total Request Count)\n\nWhere thresholds are the number of requests that were served under p50, p90 and p95 respectively.",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "(\n    sum by (program, le) (histogram_quantile(0.5, increase(http_requests_duration_milliseconds_bucket{status=~\"2..\", program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[5m]))) * 1 \n    + \n    sum by (program, le) (histogram_quantile(0.9, increase(http_requests_duration_milliseconds_bucket{status=~\"2..\", program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[5m]))) * 0.5\n) \n/ \nsum by (program, le) (histogram_quantile(0.99, increase(http_requests_duration_milliseconds_bucket{status=~\"2..\", program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[5m])))",
     "legendFormat": "{{program}}"
    }
   ]
  },
  {
   "title": "Success Rate (Over Last 5 Mins)",
   "type": "stat",
   "description": "This metric measures the rate or percentage of successful operations or transactions.\n\nAggregation: Typically, success rate is calculated as the ratio of successful operations to the total number of operations within a given timeframe.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"2.*\", program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[5m])) by (program) / sum(rate(http_requests_total{program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[5m])) by (program) ) * 100 "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Throughput is a way to measure the amount of work this service is handling. It measures how many requests are being processed per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (program) (increase(http_requests_total{program=~\"$program\", environment=~\"$environment\", version=~\"$version\"}[1m]))",
     "legendFormat": "{{program}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "This chart shows the percentage of transactions that resulted in an error. For more detail about how APM reports errors, and to learn how to set up your own error-reporting",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (program) (increase(http_requests_total{status=~\"5..\", program=~\"$program\", version=~\"$version\", environment=\"$environment\"}[1m])) or 0 / sum by (program) (increase(http_requests_total{program=\"$program\", version=~\"$version\", environment=\"$environment\"}[1m])) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Transactions 5 most time consuming (p99)",
   "type": "timeseries",
   "description": "A transaction is the activity that begins when your service receives a request and ends when it sends a response. Use this display, and the displays for database operations and external services, to understand your transaction performance.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile (0.99, sum by (method, path, le) (increase(http_requests_duration_milliseconds_bucket{program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[1m]))))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "Database Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Database Operations (Top 5 Slow Queries)",
   "type": "timeseries",
   "description": "This shows the performance of the database queries made by your service. Use this to find slow query groups and help troubleshoot slow transactions.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile (0.99, sum by (query, le) (increase(db_requests_duration_milliseconds_bucket{program=~\"$program\", version=~\"$version\", environment=~\"$environment\"}[1m]))))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  { "title": "Infrastructure Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "description": "This metric measures the percentage of CPU utilization on a system or node.\n\nAggregation: The CPU utilization percentage is typically calculated as the ratio of the time the CPU spends executing processes to the total time within a given timeframe, multiplied by 100. It is commonly aggregated using methods such as average.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (increase(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"})[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "description": "This metric measures the percentage of memory utilization on a system or node.\n\nAggregation: The memory utilization percentage is typically calculated as the ratio of the used memory to the total available memory on a node, multiplied by 100. It can be aggregated using methods such as average.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"}) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}